### ISSUE TITLE
Authentication fails in ErrorException

### ISSUE THREAD

**Issue by danipolo** [sirthxalot/laravel-parse#6]
Hi,

When I install it in a fresh Laravel I got this error trying to login:

```
(1/1) ErrorException
call_user_func_array() expects parameter 1 to be a valid callback, class 'Parse\ParseUser' does not have a method 'newQuery'
in ObjectModel.php (line 475)
at HandleExceptions->handleError(2, 'call_user_func_array() expects parameter 1 to be a valid callback, class \'Parse\\ParseUser\' does not have a method \'newQuery\'', '/var/www/html/vendor/sirthxalot/laravel-parse/src/Sirthxalot/Parse/ObjectModel.php', 475, array('method' => 'newQuery', 'params' => array(), 'this' => object(User)))
```

I'm doing something wrong?

Thanks

**Comment by sirthxalot** [comment]
Hi @danipolo 

Did you follow the instructions from: https://sirthxalot.gitbooks.io/laravel-parse/content/authentication.html

You will need to determine the config driver and implement the `use Sirthxalot\Parse\Auth\UserModel as Authenticatable` in your `User`.

Which Laravel version are you using. At this point I only tested on Laravel 5.4.19, I wasn't able to check out the new Laravel version yet.

**Comment by danipolo** [comment]
I did it.

http://imgur.com/a/jvRTW

Latest Laravel version.

I'm missing something?

**Comment by sirthxalot** [comment]
Hmm I tried out to reproduce your issue.

I have installed a fresh laravel application using v.5.4.25 and setup everything and it worked?

I will try to capture my screen and upload it so you can follow my steps.

**Comment by danipolo** [comment]
Yes please, looks very interesting.

**Comment by sirthxalot** [comment]
My internet connectivity is to slow at the moment in order to upload the movies, you will have to wait till tommorow when I am back in the office.

How does your login look like, did you tried out the routing example: https://sirthxalot.gitbooks.io/laravel-parse/content/authentication.html#a-simple-login-example

**Comment by danipolo** [comment]
Exactly what you have in this example.

Do you have any working example on Github? I will compare it.

Thanks!

**Comment by sirthxalot** [comment]
Did you tried to add the master key to your `User` model?

``` php
<?php namespace App;

use Illuminate\Notifications\Notifiable;
use Sirthxalot\Parse\Auth\UserModel as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    protected static $defaultUseMasterKey = true;
    
}
```

And try to set your config in your `.env` file, is your master key correct?:

```
PARSE_APP_ID="your-app-id"
PARSE_REST_KEY="your-rest-key"
PARSE_MASTER_KEY="your-master-key"
PARSE_SERVER_URL="https://api.parse.com/"
PARSE_MOUNT_PATH="/parse"
```

**Comment by sirthxalot** [comment]
Did it help?

**Comment by danipolo** [comment]
No..... :(

Here I share all the code... Maybe I'm missing something:

https://github.com/danipolo/parse-connector

What I forget?

**Comment by sirthxalot** [comment]
Okay now I see another issue which I could solve by removing the `parse.php` configuration file stored at:
https://github.com/danipolo/parse-connector/blob/master/config/parse.php

After removing the config and setting up the Parse environment configuration, everything worked?

- so please remove the `parse.php` configuration file.

**Comment by danipolo** [comment]
Ok, working now :)

I followed your guide, maybe need to modify the documentation.

Thank you very much!

**Comment by sirthxalot** [comment]
Yes I am sorry for this I usually don't publish the configuration. Thank you anyway for reporting the bug with configuration file and for using my package.

I will try to solve the issue as soon as possible, till than hope you can work with this version.
