### ISSUE TITLE
Dead link to documentation

### ISSUE THREAD

**Issue by proverbial-ninja** [sirthxalot/laravel-parse#9]

**Comment by sirthxalot** [comment]
Thank you @kmarima for your information and interest in Laravel-Parse.

Yes I am aware that the documentation is missing. Unfortunately I have lost the documentation, so I will need to rewrite it. I am on the track but maybe you will need to wait for at least two weeks - I am sorry for that.

But maybe I can help you out with something in the meantime. Yes I am aware that the setup is a pain without information, so may I can help you. Please describe what you want to do and I will try to respond asap.

In the meantime please hang in there and again I apologize!

Best regards
Alexander Bösch (sirthxalot)

**Comment by sirthxalot** [comment]
Documentation is available at: http://laravel-parse.readthedocs.io/en/latest/
API is available at: https://sirthxalot.github.io/laravel-parse-api/master/

Hope you like it - I am going to close this issue.
